package main

import (
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Repeat markers in the generated TypeScript schema.
const (
	schemaList = 1
	schemaMap  = 2
)

// generateSchemaTS renders a TypeScript module describing every message and RPC method,
// so a browser client can translate between field names and the field numbers used on the wire.
// Well-known types are left out: their JSON form carries no field keys.
func generateSchemaTS(files []*protogen.File) string {
	messages := map[string]string{}
	methods := map[string]string{}

	var visit func(m *protogen.Message)
	visit = func(m *protogen.Message) {
		if m.Desc.IsMapEntry() || isWellKnown(m.Desc.FullName()) {
			return
		}
		fields := map[int32]string{}
		for _, f := range m.Fields {
			fields[int32(f.Desc.Number())] = schemaField(f.Desc)
		}
		messages[string(m.Desc.FullName())] = mapFieldsString(fields)
		for _, nested := range m.Messages {
			visit(nested)
		}
	}

	for _, file := range files {
		if isWellKnown(file.Desc.FullName() + ".x") {
			continue
		}
		for _, m := range file.Messages {
			visit(m)
		}
		for _, s := range file.Services {
			for _, m := range s.Methods {
				methods[string(s.Desc.Name())+"."+string(m.Desc.Name())] =
					fmt.Sprintf("[%q, %q]", m.Input.Desc.FullName(), m.Output.Desc.FullName())
			}
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by protoc-gen-go-xrpc. DO NOT EDIT.\n\n")
	b.WriteString("/** [json name, message type of the value, 1 = repeated | 2 = map]; the key is the field number. */\n")
	b.WriteString("export type FieldSchema = [name: string, type?: string, repeat?: 1 | 2];\n\n")
	b.WriteString("export const messages: Record<string, Record<number, FieldSchema>> = {\n")
	for _, name := range sortedKeys(messages) {
		fmt.Fprintf(&b, "  %q: {%s},\n", name, messages[name])
	}
	b.WriteString("};\n\n")
	b.WriteString("/** RPC methods by \"Service.Method\": [request type, response type]. */\n")
	b.WriteString("export const methods: Record<string, [input: string, output: string]> = {\n")
	for _, name := range sortedKeys(methods) {
		fmt.Fprintf(&b, "  %q: %s,\n", name, methods[name])
	}
	b.WriteString("};\n")
	return b.String()
}

func isWellKnown(name protoreflect.FullName) bool {
	return strings.HasPrefix(string(name), "google.protobuf.")
}

func schemaField(fd protoreflect.FieldDescriptor) string {
	name := fmt.Sprintf("%q", fd.JSONName())
	switch {
	case fd.IsMap():
		if v := fd.MapValue().Message(); v != nil && !isWellKnown(v.FullName()) {
			return fmt.Sprintf("[%s, %q, %d]", name, v.FullName(), schemaMap)
		}
	case fd.Message() != nil && !isWellKnown(fd.Message().FullName()):
		if fd.IsList() {
			return fmt.Sprintf("[%s, %q, %d]", name, fd.Message().FullName(), schemaList)
		}
		return fmt.Sprintf("[%s, %q]", name, fd.Message().FullName())
	}
	return "[" + name + "]"
}

func mapFieldsString(fields map[int32]string) string {
	nums := make([]int, 0, len(fields))
	for n := range fields {
		nums = append(nums, int(n))
	}
	sort.Ints(nums)
	parts := make([]string, len(nums))
	for i, n := range nums {
		parts[i] = fmt.Sprintf("%d: %s", n, fields[int32(n)])
	}
	return strings.Join(parts, ", ")
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
